__author__ = "AlbertUnruh"
__version__ = "0.0.0a"
__license__ = "GNU AGPLv3"
__copyright__ = f"Copyright 2022-present (c) {__author__}"
__url__ = "https://github.com/AlbertUnruh/TextAdventureCreator"
__description__ = "A simple map creator for [TextAdventure](https://github.com/AlbertUnruh/TextAdventure)"
